### ISSUE TITLE
Switch to stylelint

### ISSUE THREAD

**Issue by unamaria** [drupal-graphql/drupal-decoupled-app#411]
Use [stylelint](https://stylelint.io) instead of CSSLint to avoid errors and enforce consistent conventions in stylesheets.

![screen shot 2018-04-30 at 11 25 32 pm](https://user-images.githubusercontent.com/8292440/39451887-887c5ec2-4cd0-11e8-9e44-d79e16901d91.png)

Suggestions:
* Remove CSSLint
* Use stylelint 
    * Use [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard)
* Same workflow as for js linting
* Should work for CSS under `frontend/src/**` and `backend/web/themes/**`

:)

**Comment by fubhy** [comment]
Hey Maria! There is no CSS Lint in here. Are you refering to an older version of this maybe?

**Comment by fubhy** [comment]
That's due to the version of the Drupal backend we got running in here :). Not my file! I don't have any plans of stylelint in the repo so far. I added prettier which can also be configured for CSS files. I didn't want to add eslint/stylelint, etc. because I didn't want to impose any code style outside of what prettier defaults to. Maybe I would reconsider that. Do you have any compelling arguments for adding it to the starterkit by default?

**Comment by unamaria** [comment]
Let's try 😄 
stylelint (and eslint also?) doesn't have any rules enabled by default. Of course using the standard config would already add opinions, but since they are a) pretty universal and b) rules can be easily disabled it could be considered that adding stylelint promotes healthier code without forcing code style.

**Comment by fubhy** [comment]
Okay. Let's try it then. We would have to make sure that there are no conflicts with prettier of course. Would you be up for submitting a pull request for that?

**Comment by unamaria** [comment]
Hey! I took a first stab with #412 :)

**Comment by fubhy** [comment]
Cool. Thanks! Wondering if we should also add eslint in that case :)

**Comment by unamaria** [comment]
Yay! Maybe? :)
Thank you!
